/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./../components/button/index.vue')['default']
    Card: typeof import('./../components/card/index.vue')['default']
    ConfigProvider: typeof import('./../components/configProvider/index.vue')['default']
    Dialog: typeof import('./../components/dialog/index.vue')['default']
    Draggable: typeof import('./../components/draggable/index.vue')['default']
    Drawer: typeof import('./../components/drawer/index.vue')['default']
    FormList: typeof import('./../components/formList/index.vue')['default']
    Image: typeof import('./../components/image/index.vue')['default']
    Pagination: typeof import('./../components/pagination/index.vue')['default']
    Paging: typeof import('./../components/paging/index.vue')['default']
    PlusMinus: typeof import('./../components/plusMinus/index.vue')['default']
    Space: typeof import('./../components/space/index.vue')['default']
    Table: typeof import('./../components/table/index.vue')['default']
    TableColumn: typeof import('./../components/table/tableColumn.vue')['default']
    Upload: typeof import('./../components/upload/index.vue')['default']
  }
}
